[[streamers]]
id = 0
nickname = "这是卢"
username = "不死鸟总监"
bilibili_link = "https://space.bilibili.com/406986743"
room_id = 22747736
avatar = "https://i2.hdslb.com/bfs/face/4633a8497cf1b34a8726b7a723bbd0fab286adb5.jpg"
small_avatar = "https://i2.hdslb.com/bfs/face/4633a8497cf1b34a8726b7a723bbd0fab286adb5.jpg@240w_240h_1c_1s_!web-avatar-space-header.avif"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 1
nickname = "七七"
username = "桃宫七七酱"
bilibili_link = "https://space.bilibili.com/31734139"
room_id = 23649609
avatar = "https://i1.hdslb.com/bfs/face/bcdce44b8cbe699292165bb3dd274046f9352702.jpg"
small_avatar = "https://i1.hdslb.com/bfs/face/bcdce44b8cbe699292165bb3dd274046f9352702.jpg@240w_240h_1c_1s_!web-avatar-space-header.avif"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 2
nickname = "小啾"
username = "小啾akio"
bilibili_link = "https://space.bilibili.com/415543548"
room_id = 21533102
avatar = "https://i0.hdslb.com/bfs/face/81e91eba2eeefff79f4507fe80b00ac3eb8d1f16.jpg"
small_avatar = "https://i0.hdslb.com/bfs/face/81e91eba2eeefff79f4507fe80b00ac3eb8d1f16.jpg@240w_240h_1c_1s_!web-avatar-space-header.avif"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 3
nickname = "咖米狸"
username = "咖米狸"
bilibili_link = "https://space.bilibili.com/7770395"
room_id = 14733388
avatar = "https://i2.hdslb.com/bfs/face/12922a391f707c25ef37cd6e6e390bc61d2436cc.jpg"
small_avatar = "https://i2.hdslb.com/bfs/face/12922a391f707c25ef37cd6e6e390bc61d2436cc.jpg@240w_240h_1c_1s_!web-avatar-space-header.avif"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 4
nickname = "琵琶精"
username = "陆识衣和王严言"
bilibili_link = "https://space.bilibili.com/7847261"
room_id = 24561443
avatar = "https://i0.hdslb.com/bfs/face/8385e456bc1b5b26f0c228b52a405f8aff577218.jpg"
small_avatar = "https://i0.hdslb.com/bfs/face/8385e456bc1b5b26f0c228b52a405f8aff577218.jpg@128w_128h_1c_1s.webp"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 5
nickname = "粉毛2.0"
username = "聂甯仙"
bilibili_link = "https://space.bilibili.com/3461575182649691"
room_id = 1804468097
avatar = "https://i2.hdslb.com/bfs/face/5c88955b7bc6154c7da824140af02dfd074ab621.webp"
small_avatar = "https://i2.hdslb.com/bfs/face/5c88955b7bc6154c7da824140af02dfd074ab621.webp@128w_128h_1c_1s.webp"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 6
nickname = "黑粉头子"
username = "苍天哥"
bilibili_link = "https://space.bilibili.com/671308"
room_id = 889821
avatar = "https://i1.hdslb.com/bfs/face/642f75c345c92a223f7a744b1a5ca9d19f55398e.jpg"
small_avatar = "https://i1.hdslb.com/bfs/face/642f75c345c92a223f7a744b1a5ca9d19f55398e.jpg@128w_128h_1c_1s.webp"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 7
nickname = "球仔"
username = "球仔baby"
bilibili_link = "https://space.bilibili.com/3546826892380519"
room_id = 1991476869
avatar = "https://i0.hdslb.com/bfs/face/08cff6117b96cf43be52c048f74c29935398cf20.jpg"
small_avatar = "https://i0.hdslb.com/bfs/face/08cff6117b96cf43be52c048f74c29935398cf20.jpg@128w_128h_1c_1s.webp"
description = "关注总监喵~，关注不死鸟总监喵~"

[[streamers]]
id = 8
nickname = "粉毛3.0"
username = "有希小酱"
bilibili_link = "https://space.bilibili.com/6964745"
room_id = 5611881
avatar = "https://i0.hdslb.com/bfs/face/eb7cee4cb1426647ba917de630ee07e407a29ca9.webp"
small_avatar = "https://i0.hdslb.com/bfs/face/eb7cee4cb1426647ba917de630ee07e407a29ca9.webp@128w_128h_1c_1s.webp"
description = "关注总监喵~，关注不死鸟总监喵~"
