import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ThemeProvider} from '@/context/ThemeContext';
import {GoogleAnalytics} from '@next/third-parties/google'
import "./globals.css";
import React from "react";
import {StreamerProvider} from "@/context/StreamersContext";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    referrer: "no-referrer",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="zh">
        <body className={inter.className}>
        <StreamerProvider>
        <ThemeProvider>
                    {children}
        </ThemeProvider>
        </StreamerProvider>
        </body>
        <GoogleAnalytics gaId="G-F6SKTB30TH"/>
        </html>
    );
}
