[package]
name = "statistics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
duckdb = { version = "1.0.0", features = ["bundled"] }
chrono = "0.4.38"
log = "0.4.21"
pretty_env_logger = "0.5.0"
utils = {path = "../utils"}
