name: build crawler docker image
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
jobs:
  build-rust-and-push-docker-image:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust
        run: rustup toolchain install stable
#      - name: Add rust target
#        run: rustup target add x86_64-unknown-linux-musl
#      - name: Install musl-tools
#        uses: awalsh128/cache-apt-pkgs-action@v1
#        with:
#          packages: musl-tools # provides musl-gcc
#          version: 1.0
#      - name: Install OpenSSL dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y pkg-config libssl-dev
      - name: build rust
        run: cargo build -p crawler --bin danmu --release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKERHUB_TOKEN }}
      - name: set time
        run: |
          TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d-%H-%M-%S')"
          echo "TIME=$TIME" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./crawler
          push: true
          tags: ccr.ccs.tencentyun.com/uniix-app/bilibili-monitor:carwler-${{ env.TIME }}
