name: Deploy Frontend
on:
  push:
    paths:
        - 'frontend/**'
  pull_request:
    branches:
      - master
jobs:
  Deploy-To-Cloudflare-Pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: "Deploy To Cloudflare Pages"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22
      - name: Build
        working-directory: frontend
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 5dcdb6c96e93d90e6b34559e4d307671
          projectName: bilibili-monitor
          directory: ./frontend/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"